version: '3'

services:
  ordinals-inscriber:
    build: .
    container_name: ordinals-inscriber
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
    networks:
      - ord-network
    environment:
      - NODE_ENV=production
      
  # You can uncomment this section and configure it if you have an Ordinals node
  # ord-node:
  #   image: ordinalsdev/ord:latest
  #   container_name: ord-container
  #   restart: unless-stopped
  #   volumes:
  #     - ./ord-data:/ord/data
  #   networks:
  #     - ord-network

networks:
  ord-network:
    driver: bridge