version: '3'

services:
  ordinarinos-inscription-tool:
    build:
      context: .
      dockerfile: Dockerfile.umbrel
    container_name: ordinarinos-inscription-tool
    restart: unless-stopped
    ports:
      - "3500:5000"
    volumes:
      - ./cache:/app/cache
    networks:
      - umbrel_network
    environment:
      - NODE_ENV=production
      - PORT=5000
      - USE_SIMPLIFIED_STARTUP=true
      - ORD_NODE_IP=ordinals_ord_1

networks:
  umbrel_network:
    external: true