version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.umbrel
    image: ${APP_ID}
    container_name: ${APP_ID}
    restart: on-failure
    environment:
      DIRECT_CONNECT: "true"
      BTC_SERVER_AVAILABLE: "true"
      ORD_SERVER_AVAILABLE: "true"
      BTC_RPC_USER: "${BITCOIN_RPC_USER}"
      BTC_RPC_PASSWORD: "${BITCOIN_RPC_PASS}"
      BTC_RPC_HOST: "${APP_BITCOIN_NODE_IP:-bitcoin.embassy}"
      BTC_RPC_PORT: "8332"
      ORD_RPC_HOST: "ordinals_ord_1"
      ORD_RPC_PORT: "80"
      NODE_ENV: "production"
      PORT: "3500"
    ports:
      - "3500:3500"
    volumes:
      - ${APP_DATA_DIR}/data:/ord/data
    networks:
      - default
      - embassy

networks:
  default:
    name: ${APP_ID}_default
  embassy:
    name: embassy
    external: true