version: '3'

services:
  ordinarinos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordinarinos-inscription-tool
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./cache:/app/cache
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CACHE_LIMIT_BYTES=5368709120  # 5GB cache limit
    networks:
      - ord-network

networks:
  ord-network:
    external: true